name = "kirca-api"
main = "src/index.ts"
compatibility_date = "2025-11-01"

[[d1_databases]]
binding = "DB"
database_name = "kirca-api"
database_id = "b5ddc653-b440-4cf2-94a4-61d1f6ef3be3"

[[durable_objects.bindings]]
name = "ROOM"
class_name = "Room"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["Room"]
